# Generated by Django 5.2.8 on 2025-11-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolId', models.CharField(blank=True, editable=False, max_length=4, null=True, unique=True)),
                ('userName', models.CharField(blank=True, max_length=100, null=True)),
                ('schoolName', models.CharField(max_length=150)),
                ('schoolEmail', models.EmailField(max_length=254, unique=True)),
                ('schoolContact', models.CharField(max_length=15)),
                ('schoolAddress', models.TextField()),
                ('schoolWebsite', models.URLField(blank=True, null=True)),
                ('schoolAffiliation', models.CharField(max_length=20)),
                ('schoolTrust', models.CharField(max_length=100)),
                ('schoolGstNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('schoolPrincipalName', models.CharField(max_length=100)),
                ('schoolPrincipalContact', models.CharField(max_length=15)),
                ('schoolPrincipalEmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('rollNumber', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
                ('address', models.TextField()),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='registration.schoolregistration')),
            ],
        ),
    ]
