# Generated by Django 5.2.8 on 2025-11-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolregistration',
            name='userName',
        ),
    ]
