# Generated by Django 5.2.8 on 2025-11-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_schoolregistration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('schoolAddress', models.TextField()),
                ('schoolPrincipalName', models.CharField(max_length=100)),
                ('schoolPrincipalContact', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_students', to='registration.schoolregistration')),
            ],
        ),
    ]
