# Generated by Django 5.2.8 on 2025-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_pendingstudentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingstudentregistration',
            name='schoolName',
            field=models.CharField(max_length=100),
        ),
    ]
